2024-08-19 15:11:37 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 16:54:52 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 16:54:52 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 17:16:19 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 17:33:11 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 18:31:28 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 19:11:32 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 19:11:32 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 20:07:37 | ERROR | stderr | /env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/helpers.py:974: UserWarning:
2024-08-19 20:07:37 | ERROR | stderr | 
2024-08-19 20:07:37 | ERROR | stderr | Unexpected argument. Filling with None.
2024-08-19 20:07:37 | ERROR | stderr | 
2024-08-19 20:07:37 | ERROR | stderr | Traceback (most recent call last):
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
2024-08-19 20:07:37 | ERROR | stderr |     response = await route_utils.call_process_api(
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
2024-08-19 20:07:37 | ERROR | stderr |     output = await app.get_blocks().process_api(
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
2024-08-19 20:07:37 | ERROR | stderr |     result = await self.call_function(
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/blocks.py", line 1520, in call_function
2024-08-19 20:07:37 | ERROR | stderr |     prediction = await utils.async_iteration(iterator)
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/utils.py", line 663, in async_iteration
2024-08-19 20:07:37 | ERROR | stderr |     return await iterator.__anext__()
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/utils.py", line 656, in __anext__
2024-08-19 20:07:37 | ERROR | stderr |     return await anyio.to_thread.run_sync(
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-08-19 20:07:37 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
2024-08-19 20:07:37 | ERROR | stderr |     return await future
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
2024-08-19 20:07:37 | ERROR | stderr |     result = context.run(func, *args)
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/utils.py", line 639, in run_sync_iterator_async
2024-08-19 20:07:37 | ERROR | stderr |     return next(iterator)
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/utils.py", line 801, in gen_wrapper
2024-08-19 20:07:37 | ERROR | stderr |     response = next(iterator)
2024-08-19 20:07:37 | ERROR | stderr |   File "/data/niklas/arena/ui.py", line 928, in clustering_side_by_side
2024-08-19 20:07:37 | ERROR | stderr |     generated_image0, generated_image1, model_name0, model_name1 = gen_func(state0.prompts, model_name0, model_name1, ncluster, ndim=ndim.split(" ")[0], dim_method=dim_method, clustering_method=clustering_method)
2024-08-19 20:07:37 | ERROR | stderr |   File "/data/niklas/arena/models.py", line 269, in clustering_parallel
2024-08-19 20:07:37 | ERROR | stderr |     results = [future.result() for future in futures]
2024-08-19 20:07:37 | ERROR | stderr |   File "/data/niklas/arena/models.py", line 269, in <listcomp>
2024-08-19 20:07:37 | ERROR | stderr |     results = [future.result() for future in futures]
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/concurrent/futures/_base.py", line 458, in result
2024-08-19 20:07:37 | ERROR | stderr |     return self.__get_result()
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/concurrent/futures/_base.py", line 403, in __get_result
2024-08-19 20:07:37 | ERROR | stderr |     raise self._exception
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/concurrent/futures/thread.py", line 58, in run
2024-08-19 20:07:37 | ERROR | stderr |     result = self.fn(*self.args, **self.kwargs)
2024-08-19 20:07:37 | ERROR | stderr |   File "/data/niklas/arena/models.py", line 317, in clustering
2024-08-19 20:07:37 | ERROR | stderr |     data["cluster"] = KMeans(n_clusters=ncluster, n_init='auto', random_state=0).fit_predict(emb).tolist()
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py", line 1071, in fit_predict
2024-08-19 20:07:37 | ERROR | stderr |     return self.fit(X, sample_weight=sample_weight).labels_
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/sklearn/base.py", line 1474, in wrapper
2024-08-19 20:07:37 | ERROR | stderr |     return fit_method(estimator, *args, **kwargs)
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py", line 1490, in fit
2024-08-19 20:07:37 | ERROR | stderr |     self._check_params_vs_input(X)
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py", line 1431, in _check_params_vs_input
2024-08-19 20:07:37 | ERROR | stderr |     super()._check_params_vs_input(X, default_n_init=10)
2024-08-19 20:07:37 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/sklearn/cluster/_kmeans.py", line 879, in _check_params_vs_input
2024-08-19 20:07:37 | ERROR | stderr |     raise ValueError(
2024-08-19 20:07:37 | ERROR | stderr | ValueError: n_samples=2 should be >= n_clusters=4.
2024-08-19 20:07:40 | ERROR | stderr | Traceback (most recent call last):
2024-08-19 20:07:40 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/queueing.py", line 536, in process_events
2024-08-19 20:07:40 | ERROR | stderr |     response = await route_utils.call_process_api(
2024-08-19 20:07:40 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/route_utils.py", line 276, in call_process_api
2024-08-19 20:07:40 | ERROR | stderr |     output = await app.get_blocks().process_api(
2024-08-19 20:07:40 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/blocks.py", line 1923, in process_api
2024-08-19 20:07:40 | ERROR | stderr |     result = await self.call_function(
2024-08-19 20:07:40 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/blocks.py", line 1508, in call_function
2024-08-19 20:07:40 | ERROR | stderr |     prediction = await anyio.to_thread.run_sync(  # type: ignore
2024-08-19 20:07:40 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/anyio/to_thread.py", line 56, in run_sync
2024-08-19 20:07:40 | ERROR | stderr |     return await get_async_backend().run_sync_in_worker_thread(
2024-08-19 20:07:40 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 2144, in run_sync_in_worker_thread
2024-08-19 20:07:40 | ERROR | stderr |     return await future
2024-08-19 20:07:40 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 851, in run
2024-08-19 20:07:40 | ERROR | stderr |     result = context.run(func, *args)
2024-08-19 20:07:40 | ERROR | stderr |   File "/env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/utils.py", line 818, in wrapper
2024-08-19 20:07:40 | ERROR | stderr |     response = f(*args, **kwargs)
2024-08-19 20:07:40 | ERROR | stderr |   File "/data/niklas/arena/ui.py", line 876, in check_input_clustering
2024-08-19 20:07:40 | ERROR | stderr |     if (state) and (hasattr(state, "prompts")) and (txt in state.prompts): raise gr.Warning("Text already added.")
2024-08-19 20:07:40 | ERROR | stderr | TypeError: exceptions must derive from BaseException
2024-08-19 20:10:00 | ERROR | stderr | /env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/helpers.py:974: UserWarning:
2024-08-19 20:10:00 | ERROR | stderr | 
2024-08-19 20:10:00 | ERROR | stderr | Unexpected argument. Filling with None.
2024-08-19 20:10:00 | ERROR | stderr | 
2024-08-19 20:11:31 | ERROR | stderr | /env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/helpers.py:974: UserWarning:
2024-08-19 20:11:31 | ERROR | stderr | 
2024-08-19 20:11:31 | ERROR | stderr | Unexpected argument. Filling with None.
2024-08-19 20:11:31 | ERROR | stderr | 
2024-08-19 20:50:52 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 20:50:52 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 20:51:48 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 20:53:56 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 20:54:43 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 20:55:13 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 20:55:13 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-19 20:57:06 | ERROR | stderr | 
2024-08-19 20:57:06 | ERROR | stderr |  ... (more hidden) ...
2024-08-19 20:57:06 | ERROR | stderr | 
2024-08-19 20:57:06 | ERROR | stderr | 
2024-08-19 20:57:06 | ERROR | stderr |  ... (more hidden) ...
2024-08-19 20:57:06 | ERROR | stderr | 
2024-08-19 20:57:06 | ERROR | stderr | 
2024-08-19 20:57:06 | ERROR | stderr |  ... (more hidden) ...
2024-08-19 20:57:07 | ERROR | stderr |  ... (more hidden) ...
2024-08-19 20:57:07 | ERROR | stderr | 
2024-08-19 20:57:27 | ERROR | stderr | 
2024-08-19 20:57:27 | ERROR | stderr |  ... (more hidden) ...
2024-08-19 20:57:27 | ERROR | stderr | 
2024-08-19 20:57:27 | ERROR | stderr | 
2024-08-19 20:57:27 | ERROR | stderr |  ... (more hidden) ...
2024-08-19 20:57:27 | ERROR | stderr | 
2024-08-19 20:57:27 | ERROR | stderr | 
2024-08-19 20:57:27 | ERROR | stderr |  ... (more hidden) ...
2024-08-19 20:57:27 | ERROR | stderr | 
2024-08-20 03:52:08 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 03:52:08 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 07:24:29 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 08:05:12 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 08:24:28 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 08:26:38 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 09:46:22 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 09:47:01 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 09:47:01 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 09:48:35 | ERROR | stderr | 
2024-08-20 09:48:35 | ERROR | stderr | Split strings:   0%|                                                                           | 0/1 [00:00<?, ?it/s]
2024-08-20 09:48:35 | ERROR | stderr | 
2024-08-20 09:48:35 | ERROR | stderr | 
2024-08-20 09:48:35 | ERROR | stderr | Stem Tokens:   0%|                                                                             | 0/1 [00:00<?, ?it/s]
2024-08-20 09:48:35 | ERROR | stderr | 
2024-08-20 09:48:35 | ERROR | stderr | 
2024-08-20 09:48:35 | ERROR | stderr | BM25S Retrieve:   0%|                                                                          | 0/1 [00:00<?, ?it/s]
2024-08-20 09:48:36 | ERROR | stderr | BM25S Retrieve: 100%|██████████████████████████████████████████████████████████████████| 1/1 [00:00<00:00,  3.11it/s]
2024-08-20 09:48:36 | ERROR | stderr | 
2024-08-20 09:49:08 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 10:36:14 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 12:15:59 | ERROR | stderr | /data/niklas/arena/models.py:383: UserWarning:
2024-08-20 12:15:59 | ERROR | stderr | 
2024-08-20 12:15:59 | ERROR | stderr | The use of `x.T` on tensors of dimension other than 2 to reverse their shape is deprecated and it will throw an error in a future release. Consider `x.mT` to transpose batches of matrices or `x.permute(*torch.arange(x.ndim - 1, -1, -1))` to reverse the dimensions of a tensor. (Triggered internally at ../aten/src/ATen/native/TensorShape.cpp:3675.)
2024-08-20 12:15:59 | ERROR | stderr | 
2024-08-20 12:41:22 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 12:44:09 | ERROR | stderr | /env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/helpers.py:974: UserWarning:
2024-08-20 12:44:09 | ERROR | stderr | 
2024-08-20 12:44:09 | ERROR | stderr | Unexpected argument. Filling with None.
2024-08-20 12:44:09 | ERROR | stderr | 
2024-08-20 13:14:14 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 13:14:14 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 13:15:15 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 13:15:15 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 13:47:36 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 13:47:43 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 13:47:43 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 13:48:51 | ERROR | stderr | 
2024-08-20 13:48:51 | ERROR | stderr | Split strings:   0%|                                                                           | 0/1 [00:00<?, ?it/s]
2024-08-20 13:48:51 | ERROR | stderr | 
2024-08-20 13:48:51 | ERROR | stderr | 
2024-08-20 13:48:51 | ERROR | stderr | Stem Tokens:   0%|                                                                             | 0/1 [00:00<?, ?it/s]
2024-08-20 13:48:51 | ERROR | stderr | 
2024-08-20 13:48:51 | ERROR | stderr | 
2024-08-20 13:48:51 | ERROR | stderr | BM25S Retrieve:   0%|                                                                          | 0/1 [00:00<?, ?it/s]
2024-08-20 13:48:51 | ERROR | stderr | 
2024-08-20 14:14:27 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 14:14:27 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 14:15:20 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 14:15:20 | ERROR | index_logger | Error in find_neighbors: 503 recvmsg:Connection reset by peer. Retries left: 4
2024-08-20 14:25:58 | ERROR | stderr | /env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/helpers.py:974: UserWarning:
2024-08-20 14:25:58 | ERROR | stderr | 
2024-08-20 14:25:58 | ERROR | stderr | Unexpected argument. Filling with None.
2024-08-20 14:25:58 | ERROR | stderr | 
2024-08-20 14:28:51 | ERROR | stderr | /env/lib/conda/gritkto/lib/python3.10/site-packages/gradio/helpers.py:974: UserWarning:
2024-08-20 14:28:51 | ERROR | stderr | 
2024-08-20 14:28:51 | ERROR | stderr | Unexpected argument. Filling with None.
2024-08-20 14:28:51 | ERROR | stderr | 
